services:
  db:
    image: postgres:16
    container_name: siq_postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: siq_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
